---
- hosts: ruby
  sudo: yes
  gather_facts: no
  tasks:
    - shell: ruby --version
      register: ruby_version_check
      ignore_errors: yes

    - include: tasks/compile.yml
      when: ruby_version_check|failed

    - include: tasks/gem.yml
