---
- hosts: sensu-client
  sudo: yes
  tasks:
    - name: git clone/pull sensu-community-plugins
      git:
        repo=git://github.com/sensu/sensu-community-plugins.git
        dest=/etc/sensu/community-plugins
        accept_hostkey=yes
        force=yes

    - name: chmod +x plugins
      shell: find /etc/sensu/community-plugins/plugins -type f | xargs chmod 755
