- hosts: sensu-client
  sudo: yes
  tasks:
    - include: tasks/sensu-client.yml
    - include: tasks/ruby.yml
    - include: tasks/sensu-community-plugins.yml
    - name: Start Sensu services
      service:
        name=sensu-client
        enabled=yes
        state=restarted
