---
- hosts: sensu-client
  sudo: yes
  gather_facts: no
  tasks:
    - name: configure sensu connections
      template:
        src=templates/{{item}}.json.j2
        dest=/etc/sensu/conf.d/{{item}}.json
        owner=sensu
        group=sensu
        mode=0644
      with_items:
        - rabbitmq
        - client

    - include: tasks/plugins.yml
    - include: tasks/restart.yml
