- hosts: sensu-client
  sudo: yes
  tasks:
    - command: test -f /etc/apt/sources.list.d/sensu.list
      register: install_check
      ignore_errors: yes
    - include: tasks/sensu-client.yml
      when: install_check|failed
    - include: tasks/sensu-community-plugins.yml
    - name: Restart Sensu services
      service:
        name=sensu-client
        enabled=yes
        state=restarted
