---
- hosts: sensu-client
  sudo: yes
  tasks:
    - command: test -f /etc/apt/sources.list.d/sensu.list
      register: install_check
      ignore_errors: yes

    - include: tasks/client.yml
      when: install_check|failed

    - include: tasks/community-plugins.yml
    - include: tasks/restart.yml
