---
- hosts: kibana
  sudo: yes
  gather_facts: no
  vars:
    colors:
      - "#bc3539"
      - "#d9a831"
      - "#59cb8a"
      - "#449ad6"
      - "#7f7f7f"
  tasks:
    - name: create dashboards.json
      template:
        src=templates/dashboards.json.j2
        dest=/opt/kibana/app/dashboards/dashboards.json
        owner=root
        group=root
        mode=0644

    - name: create each nginx.json
      template:
        src=templates/nginx.json.j2
        dest=/opt/kibana/app/dashboards/nginx_{{ item }}.json
        owner=root
        group=root
        mode=0644
      with_items: groups['nginx']

    - name: create statics
      template:
        src=templates/{{ item }}.json.j2
        dest=/opt/kibana/app/dashboards/{{ item }}.json
        owner=root
        group=root
        mode=0644
      with_items:
        - load-tests
        - web-servers
        - switches

    - name: create each server.json
      template:
        src=templates/server.json.j2
        dest=/opt/kibana/app/dashboards/{{ item }}.json
        owner=root
        group=root
        mode=0644
      with_items: groups['sensu-client']
