---
- hosts: kibana
  sudo: yes
  gather_facts: no
  vars:
    colors:
      - "#bc3539"
      - "#d9a831"
      - "#59cb8a"
      - "#449ad6"
      - "#7f7f7f"
  tasks:
    - name: create dashboards
      template:
        src=templates/dashboard.json.j2
        dest=/opt/kibana/app/dashboards/dashboard.json
        owner=root
        group=root
        mode=0644

    - name: create nginx
      template:
        src=templates/nginx.json.j2
        dest=/opt/kibana/app/dashboards/nginx_{{ item }}.json
        owner=root
        group=root
        mode=0644
      with_items: groups['nginx']

    - name: create switch
      template:
        src=templates/switch.json.j2
        dest=/opt/kibana/app/dashboards/switch_{{ item }}.json
        owner=root
        group=root
        mode=0644
      with_items: groups['switch']

    - name: create experiment
      template:
        src=templates/{{ item }}.json.j2
        dest=/opt/kibana/app/dashboards/{{ item }}.json
        owner=root
        group=root
        mode=0644
      with_items:
        - load-tests
        - web-servers

    - name: create each sensu.json
      template:
        src=templates/sensu.json.j2
        dest=/opt/kibana/app/dashboards/{{ item }}.json
        owner=root
        group=root
        mode=0644
      with_items: groups['sensu-client']
