---
- hosts: kibana
  sudo: yes
  gather_facts: no
  tasks:
    - name: create each host.json
      template:
        src=templates/host.json.j2
        dest=/opt/kibana/app/dashboards/{{ item }}.json
        owner=root
        group=root
        mode=0644
      with_items: groups['sensu-client']

    - name: create sensu.json
      template:
        src=templates/sensu.json.j2
        dest=/opt/kibana/app/dashboards/sensu.json
        owner=root
        group=root
        mode=0644
