---
- hosts: kibana
  sudo: yes
  gather_facts: no
  vars:
    colors:
      - "#bc3539"
      - "#d9a831"
      - "#59cb8a"
      - "#449ad6"
  tasks:
    - name: create dashboards.json
      template:
        src=templates/dashboards.json.j2
        dest=/opt/kibana/app/dashboards/dashboards.json
        owner=root
        group=root
        mode=0644

    - name: create each rails.json
      template:
        src=templates/rails.json.j2
        dest=/opt/kibana/app/dashboards/rails_{{ item }}.json
        owner=root
        group=root
        mode=0644
      with_items: groups['rails']

    - name: create load-tests.json
      template:
        src=templates/load-tests.json.j2
        dest=/opt/kibana/app/dashboards/load-tests.json
        owner=root
        group=root
        mode=0644

    - name: create switches.json
      template:
        src=templates/switches.json.j2
        dest=/opt/kibana/app/dashboards/switches.json
        owner=root
        group=root
        mode=0644

    - name: create each server.json
      template:
        src=templates/server.json.j2
        dest=/opt/kibana/app/dashboards/{{ item }}.json
        owner=root
        group=root
        mode=0644
      with_items: groups['sensu-client']
