---
- name: copy plugins
  copy:
    src=files/{{item}}
    dest=/etc/sensu/plugins/{{item}}
    owner=sensu
    group=sensu
    mode=0755
  with_items:
    - cpu-usage-metrics.sh
    - disk-usage-metrics.rb
    - memory-metrics-percent.rb
    - net-traffic-metrics.rb
    - snmp-traffic-metrics.rb
