---
- name: copy plugins
  copy:
    src=files/{{item}}
    dest=/etc/sensu/plugins/{{item}}
    owner=sensu
    group=sensu
    mode=0755
  with_items:
    - check-cpu
    - check-memory
    - check-disk
    - check-http
    - check-elasticsearch
    - check-redis
    - check-rabbitmq
    - metrics-cpu
    - metrics-memory
    - metrics-disk
    - metrics-traffic
    - metrics-snmp
