---
- name: install dependent packages
  command: apt-get -y install libssl-dev zlib1g-dev libreadline6-dev libffi-dev make

- name: download source code
  shell:
    wget http://cache.ruby-lang.org/pub/ruby/2.2/ruby-{{ruby_version}}.tar.gz && tar xf ruby-{{ruby_version}}.tar.gz
    chdir=/tmp

- name: compile & install
  shell:
    ./configure && make && make install
    chdir=/tmp/ruby-{{ruby_version}}
