---
- name: mkdir vagrant
  file:
    path={{ansible_env.HOME}}/vagrant
    state=directory

- name: scp templates/Vagrantfile vagrant/
  template:
    src=templates/Vagrantfile.j2
    dest={{ansible_env.HOME}}/vagrant/Vagrantfile
    mode=664

- name: vagrant up
  command:
    vagrant up
    chdir={{ansible_env.HOME}}/vagrant
