---
- name: scp templates/Vagrantfile vagrant/instance-*
  template:
    src=templates/Vagrantfile.j2
    dest={{ansible_env.HOME}}/vagrant/instance-{{item}}/Vagrantfile
    mode=664
  with_sequence: count={{instance_num}}

- name: box list
  shell: vagrant box list | grep {{box_name}}
  ignore_errors: yes
  register: box_list

- name: box add
  command: vagrant box add {{box_name}} {{box_url}}
  when: box_list|failed

- name: mutate --input_provider kvm libvirt
  command: vagrant mutate {{box_name}} --input_provider kvm libvirt
  when: box_list|failed
