---
- hosts: all
  sudo: yes
  gather_facts: no
  tasks:
    - name: notify to slack
      slack:
        channel={{ slack_channel }}
        icon_url='http://www.ansible.com/hs-fs/hub/330046/file-764918166-png/Official_Logos/ansible_circleA_black_small.png'
        msg='サーバーアップデートを開始します。'
        token={{ slack_token }}
        username='Ansible'
      run_once: true
      when: slack_notify

    - name: apt-get update & upgrade
      apt:
        update_cache=yes
        upgrade=dist

    - name: apt-get autoremove
      command: apt-get -y autoremove

    - name: apt-get clean
      command: apt-get -y clean

    - name: notify to slack
      slack:
        channel={{ slack_channel }}
        icon_url='http://www.ansible.com/hs-fs/hub/330046/file-764918166-png/Official_Logos/ansible_circleA_black_small.png'
        msg='サーバーアップデートが完了しました。'
        token={{ slack_token }}
        username='Ansible'
      run_once: true
      when: slack_notify
