---
- hosts: reboot
  gather_facts: no
  vars:
    colon: ':'
  tasks:
    - name: reboot
      command: /sbin/shutdown -r now
      sudo: yes

    - name: wait go down
      local_action: wait_for host={{ ansible_ssh_host }} port=22 state=stopped

    - name: wait come up
      local_action: wait_for host={{ ansible_ssh_host }} port=22 delay=30

    - name: notify to typetalk
      typetalk:
        client_id={{ typetalk_client_id }}
        client_secret={{ typetalk_client_secret }}
        topic={{ typetalk_topic }}
        msg='{{ colon }}wink{{ colon }} アップデートが完了しました! 再起動中です'
      when: typetalk_notify
