---
- hosts: reboot
  gather_facts: no
  tasks:
    - name: reboot
      command: /sbin/shutdown -r now
      sudo: yes

    - name: wait go down
      local_action: wait_for host={{ ansible_ssh_host }} port=22 state=stopped

    - name: wait come up
      local_action: wait_for host={{ ansible_ssh_host }} port=22 delay=30
